name: Install node-zlib on arm64

on:
  workflow_dispatch:

jobs:
  node-18191:
    name: Node.js 18.19.1
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '18.19.1'
      - run: npm i zlib@1.0.5

  node-20111:
    name: Node.js 20.11.1
    runs-on: macos-14
    needs: node-18191
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '20.11.1'
      - run: npm i zlib@1.0.5
      
  node-2160:
    name: Node.js 21.6.2
    runs-on: macos-14
    needs: node-20111
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '21.6.2'
      - run: npm i zlib@1.0.5


  node-18200:
    name: Node.js 18.20.0
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '18.20.0'
      - run: npm i zlib@1.0.5

  node-20120:
    name: Node.js 20.12.0
    runs-on: macos-14
    needs: node-18200
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '20.12.0'
      - run: npm i zlib@1.0.5

  node-2170:
    name: Node.js 21.7.0
    runs-on: macos-14
    needs: node-20120
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '21.7.0'
      - run: npm i zlib@1.0.5

  node-2200:
    name: Node.js 22.0.0
    runs-on: macos-14
    needs: node-2170
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '22.0.0'
      - run: npm i zlib@1.0.5


  node-18:
    name: Node.js 18 (latest)
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '18'
      - run: npm i zlib@1.0.5

  node-20:
    name: Node.js 20 (latest)
    runs-on: macos-14
    needs: node-18
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '20'
      - run: npm i zlib@1.0.5

  node-21:
    name: Node.js 21 (latest)
    runs-on: macos-14
    needs: node-20
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '21'
      - run: npm i zlib@1.0.5

  node-22:
    name: Node.js 22 (latest)
    runs-on: macos-14
    needs: node-21
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: '22'
      - run: npm i zlib@1.0.5
